version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: npm i & npm test
                command: |
                    npm i
                    npm test
